[vlive]
title = "MAGIC STRAWBERRY SOUND ─ Media Board"
url = "https://www.vlive.tv/channel/FAC8D/board/3621?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"